import torch  
  
# 假设tensor1和tensor2是你的Tensor变量  
tensor1 = torch.tensor([0, 0, 0, 0, 0, 0, 0, 9, 9, 3, 3, 1, 5, 0, 0, 7, 8, 0, 8, 0, 3, 0, 0, 3,  
                        0, 0, 7, 1, 7, 0, 9, 0], device='cuda:0')  
tensor2 = torch.tensor([4, 9, 0, 9, 8, 0, 4, 6, 0, 6, 3, 1, 5, 4, 8, 3, 3, 9, 3, 3, 3, 7, 9, 8,  
                        0, 8, 2, 1, 7, 0, 6, 5], device='cuda:0')  

tensor1_list = tensor1.cpu().tolist()
  
with open('log.txt', 'w') as file:
    file.write("generated by pytorch\n")